### PR TITLE
#345 verify that instance actually exists before going forward

### LINKED ISSUE #345: API allows getting allocation information for Nomad jobs not managed by Broccoli
## Problem

When sending a websocket message to get instance tasks, you can specify any nomad job ID as payload. As long as your user instance regex matches the payload, you will receive information about the allocated tasks of that job, independent of whether a corresponding instance exists in Broccoli.

## How to Reproduce

1. Start a nomad job called `my-http`
2. Start Broccoli, connect to the WS and send the following message
   ```
   {"messageType":"getInstanceTasks","payload":"my-http"}
   ```
3. Receive allocation info:
   ```
   {
     "messageType": "getInstanceTasksSuccess",
     "payload": {
       "instanceId": "my-http",
       "allocatedTasks": [
         {
           "taskName": "http-task",
           "taskState": "running",
           "allocationId": "f7ce9aa8-c56b-f264-ed3f-a7e7657a8982",
           "clientStatus": "running",
           "resources": {
             "cpuRequiredMhz": 50,
             "cpuUsedMhz": 65.79596670724084,
             "memoryRequiredBytes": 128000000,
             "memoryUsedBytes": 25829376
           }
         }
       ]
     }
   }
   ```

## Expected Response

```
{
  "messageType": "getInstanceTasksError",
  "payload": {
    "instanceId": "my-http",
    "error": {
      "reason": "Instance my-http not found"
    }
  }
}
```

## Solution

Validate that the requested instance is really an instance and do not just forward to Nomad.

### PR DESCRIPTION
**Pull request by FRosner**
fixes #345

### CODE REVIEW

File: server/src/test/scala/de/frosner/broccoli/instances/NomadInstancesSpec.scala [hunk 1]
```diff
@@ -64,21 +89,29 @@ class NomadInstancesSpec
       "include resources in instance tasks" in todo
 
       "fail to get instance tasks if the job wasn't found" in prop { (user: Account, id: String) =>
+        val instanceService = mock[InstanceService]
         val client = mock[NomadClient]
+
+        instanceService
```
Comment (Gerrrr) [inline server/src/test/scala/de/frosner/broccoli/instances/NomadInstancesSpec.scala]: You duplicate the mock for the `InstanceService`. What do you think about moving it into a separate function?

**Review by Gerrrr — CHANGES_REQUESTED** [review]

File: server/src/test/scala/de/frosner/broccoli/instances/NomadInstancesSpec.scala (hunk 1 above)
Comment (FRosner) [reply server/src/test/scala/de/frosner/broccoli/instances/NomadInstancesSpec.scala]: Done.

**Review by Gerrrr — APPROVED** [review]
