### PR TITLE
#241 be more resilient on parsing nomad job service responses

### LINKED ISSUE #241: Instance does not show all services
Seems that a job does not show services for some reason. After looking into it we discovered that this job was having multiple task groups. Could it be that your JSON parsing code does not work properly with multiple task groups?

https://github.com/FRosner/cluster-broccoli/blob/74e56050add6ceb760c9937145433c173a6cec1a/app/de/frosner/broccoli/services/NomadService.scala#L137

```
[ERROR] NomadService - Requesting services for service-name failed: play.api.libs.json.JsResultException: JsResultException(errors:List((,List(ValidationError(List(error.expected.jsarray),WrappedArray())))))
```

### PR DESCRIPTION
**Pull request by FRosner**
Fixes #241

### CODE REVIEW

File: test/de/frosner/broccoli/services/NomadServiceSpec.scala [hunk 1]
```diff
@@ -0,0 +1,84 @@
...
+import scala.concurrent.Await
+import scala.concurrent.duration.Duration
+
+class NomadServiceSpec extends Specification with ServiceMocks {
+
+  sequential
+
+  "Requesting services for specific job" should {
+
+    "ask consul for the services that nomad returns" in {
```
Comment (swsnr) [inline test/de/frosner/broccoli/services/NomadServiceSpec.scala:28]: Please write test descriptions based on the intended outcome not the intended procedure, eg,

```
"The Nomad service" should "provide services for a job with running consul services"

"The Nomad service" should "provide services for a job which has tasks without services"
```

File: test/de/frosner/broccoli/services/NomadServiceSpec.scala [hunk 2]
```diff
@@ -0,0 +1,84 @@
...
+          verify(consulService).requestServiceStatus(jobId, Iterable(service1.name))
+          result === Seq(service1.name)
+        }
+      }
+    }
+
+    "not explode when receiving tasks without services" in {
+      val service1 = Service("my-service")
+      val task1 = Task(Some(Seq(service1)))
+      val task2 = Task(None)
```
Comment (swsnr) [inline test/de/frosner/broccoli/services/NomadServiceSpec.scala:57]: Please find more descriptive names here, ie, "taskWithService" and "taskWithoutService" or similar.

File: test/de/frosner/broccoli/services/NomadServiceSpec.scala [hunk 3]
```diff
@@ -0,0 +1,84 @@
...
+      val taskGroup1 = TaskGroup(Some(Seq(task1)))
+      val taskGroup2 = TaskGroup(Some(Seq(task2)))
```
Comment (swsnr) [inline test/de/frosner/broccoli/services/NomadServiceSpec.scala:59]: Likewise here.

Comment (swsnr) [reply test/de/frosner/broccoli/services/NomadServiceSpec.scala:59]: Even better, do not bind task groups to names at all, since you only ever use these once.

File: test/de/frosner/broccoli/services/NomadServiceSpec.scala [hunk 4]
```diff
@@ -0,0 +1,84 @@
...
+          }
+      } { implicit port =>
+        WsTestClient.withClient { client =>
+          val configuration = Configuration.from(
+            Map(
+              conf.NOMAD_URL_KEY -> s"http://localhost:$port"
+            ))
+          val nomadService = new NomadService(configuration, consulService, client)
+          val jobId = "my-job"
+          val result = Await.result(nomadService.requestServices(jobId), Duration(5, TimeUnit.SECONDS))
```
Comment (swsnr) [inline test/de/frosner/broccoli/services/NomadServiceSpec.scala:75]: "result" -> "receivedServices".

File: app/de/frosner/broccoli/services/NomadService.scala [hunk 5]
```diff
@@ -117,43 +119,48 @@ class NomadService @Inject()(configuration: Configuration, consulService: Consul
...
-        consulService.requestServiceStatus(id, jobServiceIds)
-        setNomadReachable()
-      case Failure(throwable) =>
+    val eventuallyRequestedServices = eventuallyJobServiceIds.map { jobServiceIds =>
+      Logger.debug(s"${jobRequest.uri} => ${jobServiceIds.mkString(", ")}")
+      consulService.requestServiceStatus(id, jobServiceIds)
+      jobServiceIds
+    }
+    eventuallyRequestedServices.onFailure {
+      case throwable =>
```
Comment (swsnr) [inline app/de/frosner/broccoli/services/NomadService.scala:159]: Why do you use `case` here?  It's redundant as far as I see.

File: app/de/frosner/broccoli/services/NomadService.scala [hunk 6]
```diff
@@ -117,43 +119,48 @@ class NomadService @Inject()(configuration: Configuration, consulService: Consul
...
       }
-      case Failure(throwable) => {
+      case Failure(throwable: ConnectException) => {
         Logger.error(
           s"Failed to request statuses for ${instanceIds.mkString(", ")} from ${jobsRequest.uri}: $throwable")
         setNomadNotReachable()
       }
+      case Failure(throwable) => {
+        Logger.error(
+          s"Failed to request statuses for ${instanceIds.mkString(", ")} from ${jobsRequest.uri}: $throwable")
```
Comment (swsnr) [inline app/de/frosner/broccoli/services/NomadService.scala]: Please log different messages in these branches, as these are essentially different error conditions with different levels of "fatality".  Using different messages allows us to search for each error case in logs.

**Review by swsnr — CHANGES_REQUESTED** [review]

File: app/de/frosner/broccoli/nomad/models/Job.scala [hunk 7]
```diff
@@ -0,0 +1,15 @@
+package de.frosner.broccoli.nomad.models
+
+import play.api.libs.json._
+import play.api.libs.functional.syntax._
+
+case class Job(taskGroups: Option[Seq[TaskGroup]])
```
Comment (swsnr) [inline app/de/frosner/broccoli/nomad/models/Job.scala]: Please make case classes `final`, to prevent accidentally inheriting a case class (which you should never do, semantically)

File: app/de/frosner/broccoli/nomad/models/Service.scala [hunk 8]
```diff
@@ -0,0 +1,15 @@
+package de.frosner.broccoli.nomad.models
+
+import play.api.libs.json._
+import play.api.libs.functional.syntax._
+
+case class Service(name: String)
```
Comment (swsnr) [inline app/de/frosner/broccoli/nomad/models/Service.scala]: Likewise, please make this case class `final`.

File: app/de/frosner/broccoli/nomad/models/Task.scala [hunk 9]
```diff
@@ -0,0 +1,15 @@
+package de.frosner.broccoli.nomad.models
+
+import play.api.libs.json._
+import play.api.libs.functional.syntax._
+
+case class Task(services: Option[Seq[Service]])
```
Comment (swsnr) [inline app/de/frosner/broccoli/nomad/models/Task.scala]: And this case class as well :)

File: app/de/frosner/broccoli/nomad/models/TaskGroup.scala [hunk 10]
```diff
@@ -0,0 +1,15 @@
+package de.frosner.broccoli.nomad.models
+
+import play.api.libs.json._
+import play.api.libs.functional.syntax._
+
+case class TaskGroup(tasks: Option[Seq[Task]])
```
Comment (swsnr) [inline app/de/frosner/broccoli/nomad/models/TaskGroup.scala]: And this one, too :)

**Review by swsnr — CHANGES_REQUESTED** [review]
Please make all case classes `final` to prevent inheritance from case classes.

File: app/de/frosner/broccoli/services/NomadService.scala (hunk 5 above)
Comment (FRosner) [reply app/de/frosner/broccoli/services/NomadService.scala:159]: image

Comment (swsnr) [reply app/de/frosner/broccoli/services/NomadService.scala:159]: Ah, sorry, didn't know `onFailure` used a partial function.  Sorry for the noise
