### PR TITLE
Issue 337

### LINKED ISSUE #337: Use atomic move operation in file system instance storage
### Problem

Right now, if Broccoli crashes during a [write operation](https://github.com/FRosner/cluster-broccoli/blob/1165d42c61c9bb47c52a2ee19c21a2e8ae09c4ed/server/src/main/scala/de/frosner/broccoli/instances/storage/filesystem/FileSystemInstanceStorage.scala#L80) using the file system instance storage, this might lead to corrupted data.

### Solution

- Create `<instance-id>.json_tmp` inside the instance dir and write the content there.
- Use [`Files.move`](https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#move(java.nio.file.Path,%20java.nio.file.Path,%20java.nio.file.CopyOption...)) with [`StandardCopyOption.ATOMIC_MOVE`](https://docs.oracle.com/javase/7/docs/api/java/nio/file/StandardCopyOption.html#ATOMIC_MOVE) to overwrite `<instance-id>.json` afterwards.

### PR DESCRIPTION
**Pull request by IshmeetKaur**
Use atomic move operation in file system instance storage

fixes #337

### CODE REVIEW

File: server/src/main/scala/de/frosner/broccoli/instances/storage/filesystem/FileSystemInstanceStorage.scala [hunk 1]
```diff
@@ -79,11 +82,13 @@ class FileSystemInstanceStorage(storageDirectory: File) extends InstanceStorage
   @volatile
   override def writeInstanceImpl(instance: Instance): Try[Instance] = {
     val id = instance.id
-    val file = idToFile(id)
```
Comment (FRosner) [inline server/src/main/scala/de/frosner/broccoli/instances/storage/filesystem/FileSystemInstanceStorage.scala:82]: Please call it `tempFile` to make it more obvious that it is temporary.

File: server/src/main/scala/de/frosner/broccoli/instances/storage/filesystem/FileSystemInstanceStorage.scala [hunk 2]
```diff
@@ -79,11 +82,13 @@ class FileSystemInstanceStorage(storageDirectory: File) extends InstanceStorage
...
+    val file = idToFileTemp(id)
     val printStream = Try(new PrintStream(new FileOutputStream(file)))
     val afterWrite = printStream.map(_.append(Json.toJson(instance).toString()))
-    printStream.map(_.close())
-    afterWrite.map(_ => instance)
+    val finishWrite = printStream.map(_.close())
```
Comment (FRosner) [inline server/src/main/scala/de/frosner/broccoli/instances/storage/filesystem/FileSystemInstanceStorage.scala]: I guess we should map based on `afterWrite` to also catch if appending breaks.

File: server/src/main/scala/de/frosner/broccoli/instances/storage/filesystem/FileSystemInstanceStorage.scala [hunk 3]
```diff
@@ -79,11 +82,13 @@ class FileSystemInstanceStorage(storageDirectory: File) extends InstanceStorage
...
+    val finishMove = finishWrite.flatMap(_ =>
+      Try(Files.move(idToFileTemp(id).toPath, idToFile(id).toPath, StandardCopyOption.ATOMIC_MOVE)))
```
Comment (FRosner) [inline server/src/main/scala/de/frosner/broccoli/instances/storage/filesystem/FileSystemInstanceStorage.scala]: Please reuse the variable you created instead of again generating the file name with `idToFileTemp(id)`.

File: server/src/main/scala/de/frosner/broccoli/instances/storage/filesystem/FileSystemInstanceStorage.scala [hunk 4]
```diff
@@ -26,6 +27,8 @@ class FileSystemInstanceStorage(storageDirectory: File) extends InstanceStorage
     throw new IllegalStateException(s"Cannot lock $storageDirectory. Is there another Broccoli instance running?")
   }
 
+  def idToFileTemp(id: String): File = new File(storageDirectory, id + ".json_tmp")
```
Comment (FRosner) [inline server/src/main/scala/de/frosner/broccoli/instances/storage/filesystem/FileSystemInstanceStorage.scala]: Should be called `idToTempFile`, no?

**Review by FRosner — CHANGES_REQUESTED** [review]

File: server/src/main/scala/de/frosner/broccoli/instances/storage/filesystem/FileSystemInstanceStorage.scala (hunk 2 above)
Comment (FRosner) [reply server/src/main/scala/de/frosner/broccoli/instances/storage/filesystem/FileSystemInstanceStorage.scala]: Sorry I might have been confused here. If we map it on `finishWrite` we'll not have the error when appending.

Let's quickly look at it together on Monday.

Comment (IshmeetKaur) [reply server/src/main/scala/de/frosner/broccoli/instances/storage/filesystem/FileSystemInstanceStorage.scala]: Yes.. Sure

**Review by FRosner — DISMISSED** [review]

**Review by FRosner — APPROVED** [review]
